[workspace]
name = "Parcels"
preview = ["pixi-build"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
requires-pixi = ">=0.63.0"

[package]
name = "parcels"
version = "dynamic" # dynamic versioning needs better support in pixi https://github.com/prefix-dev/pixi/issues/2923#issuecomment-2598460666 . Putting `version = "dynamic"` here for now until pixi recommends something else.

[package.build]
backend = { name = "pixi-build-python", version = "0.4.*" }

[package.host-dependencies]
setuptools = "*"
setuptools_scm = "*"


[package.run-dependencies] # keep section in sync with pyproject.toml dependencies
python = ">=3.11"
netcdf4 = ">=1.6.0"
numpy = ">=2.1.0"
tqdm = ">=4.50.0"
xarray = ">=2024.5.0"
uxarray = ">=2025.3.0"
dask = ">=2024.5.1"
zarr = ">=2.15.0,!=2.18.0,<3"
xgcm = ">=0.9.0"
cf_xarray = ">=0.8.6"
cftime = ">=1.6.3"
pooch = ">=1.8.0"
py-triangle = ">=20250106,<20250107"

[dependencies]
parcels = { path = "." }

[feature.rattler-build.dependencies]
python = "*"
git = "*"
rattler-build = "*"

[feature.rattler-build.tasks]
get-parcels-alpha-version = { cmd = "python tools/get-parcels-alpha-version.py" }
build-parcels = { cmd = "rattler-build build --recipe .github/ci/recipe.yaml", description = "Build the Parcels conda package" }

[feature.minimum.dependencies]
python = "3.11.*"
netcdf4 = "1.6.*"
numpy = "2.1.*"
tqdm = "4.50.*"
xarray = "2024.5.*"
uxarray = "2025.3.*"
dask = "2024.5.*"
zarr = "2.15.*"
xgcm = "0.9.*"
cf_xarray = "0.8.*"
cftime = "1.6.*"
pooch = "1.8.*"

[environments]
test-minimum = { features = ["minimum"] }
build = { features = ["rattler-build"] }
